### ISSUE TITLE
Edit mode (Global)  : 

### ISSUE THREAD

**Issue by sas2402** [InfotelGLPI/mydashboard#53]
- The version of the plugin.  = Version 1.6.2
- The version of your GLPI. = 9.3.1
.

Error open main page
Edit mode (Global)  : 
Fatal error: Uncaught Error: Call to undefined method Profile::getUnderActiveProfileRestrictCriteria() in /var/www/glpi/plugins/mydashboard/inc/menu.class.php:282 Stack trace: #0 /var/www/glpi/plugins/mydashboard/inc/menu.class.php(388): PluginMydashboardMenu::dropdownProfiles(Array) #1 /var/www/glpi/plugins/mydashboard/inc/menu.class.php(324): PluginMydashboardMenu->displayEditMode('2', '4', 0, 1683593907) #2 /var/www/glpi/plugins/mydashboard/inc/menu.class.php(243): PluginMydashboardMenu->showDashboard('4', 0, 1683593907) #3 /var/www/glpi/plugins/mydashboard/inc/menu.class.php(1073): PluginMydashboardMenu->showMenu('2', '4', 0, 1683593907) #4 /var/www/glpi/plugins/mydashboard/front/menu.php(116): PluginMydashboardMenu->loadDashboard('4', 0) #5 {main} thrown in /var/www/glpi/plugins/mydashboard/inc/menu.class.php on line 282

**Comment by keha35** [comment]
Can you try with the release 1.6.4
